[features]
seeds = false
[programs.devnet]
vaccinebackend = "HCjp3FqbKxuHbxrSSMDE7DEzY3jkprmF5vfchJoFEwcE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/robertkottelin/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
